### ISSUE TITLE
Need more than 6 axis

### ISSUE THREAD

**Issue by smitty97** [TheFlyingDutchman77/EasyControlsMSFS#1]
Currently i use vjoy to combine multiple joysticks into one, so that in msfs i dont have to make multiple profile changes when i fly a different aircraft.  I'd like to continue to use vjoy because of its smoothing/exponential functions, but i have more than 6 axes.  Also, trying to save after clicking 'axis 4-6' crashes the program.

**Comment by TheFlyingDutchman77** [comment]
Unfortunately, no plans add the moment to add more than 6 axis. The whole idea of this program is to have individual assignments per joystick, so you should not combine them in 1 vjoy when using this program. 

I haven't received other CTDs when saving with 4-6 axis, but will check that.

**Comment by TheFlyingDutchman77** [comment]
Just checked, no crash for me when saving assignments for 4-6 axis. So closing the issue for now.
