### ISSUE TITLE
FBW A32NX custom events not working

### ISSUE THREAD

**Issue by Engin1980** [TheFlyingDutchman77/EasyControlsMSFS#2]
Hi, thank you for your great work.

I am trying to get your solution working with FBW A32NX. Do you use that plane too? Can you please check if custom events of the FBW plane work too? E.g. Mobiflight.A32NX.FCU_ALT_PULL, Mobiflight.A32NX.FCU_AP_2_PUSH? Thank you in advance

**Comment by TheFlyingDutchman77** [comment]
I don't fly the FBW, but all Mobiflight events should work, as long as they are in your Mobiflight events file. I use Mobiflight a lot for custom recente without any issue.

**Comment by Engin1980** [comment]
Eh, resolved.

Thank you for your response. The issue was that in the mobiflight event file were different casing of the event name than in FBW documentation.
